modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"
[[mods]]
modId="slabstoblocks_bop"
version="${file.jarVersion}"
displayName="Slabs to Blocks: Biomes O' Plenty"
logoFile="examplemod.png"
credits="Idea for this mod was from the original Slabs to Blocks by Mars"
authors="LneedhelpnowPLS"
description='''
Adds crafting recipes for making Biomes O' Plenty's slabs into their block variants.
'''
[[dependencies.slabstoblocks_bop]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"
[[dependencies.slabstoblocks_bop]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.20)"
ordering="NONE"
side="BOTH"